### ISSUE TITLE
How we can deploy *.mvir to the local validator node(s).

### ISSUE THREAD

**Issue by korrio** [etoroxlabs/etoken-libra#2]
I see the README.md only mention on how we can do `functional_test` the mvir file via

`cargo test -p functional_tests eToken`

But I'm curious that, for now. 
Can we deploy our customized mvir file to the local libra node(s) ?

What like what we can deploy our .sol on Ethereum.

**Comment by peteremiljensen** [comment]
Hi @korrio 

Thanks for your question. There are no nice guide yet, but you should be able to deploy the modules to a local libra node by the method described in the following forum post: https://community.libra.org/t/how-to-create-a-new-testnet-from-scratch/261/3

Thanks, 
Peter Emil Jensen
